apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mediawikidb.name }}
  labels:
    db: {{ .Values.mediawikidb.name }}
spec:
  type: {{ .Values.mediawikidb.service.type }}
  ports:
    - port: {{ .Values.mediawikidb.service.port }}
      targetPort: {{ .Values.mediawikidb.service.port }}
      protocol: TCP
  selector:
    db: {{ .Values.mediawikidb.name }}
